package com.database.entity;

import java.io.Serializable;

public class PlayerKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.roleId
     *
     * @mbg.generated Mon Aug 10 12:46:49 CST 2020
     */
    private Long roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.name
     *
     * @mbg.generated Mon Aug 10 12:46:49 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player
     *
     * @mbg.generated Mon Aug 10 12:46:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.roleId
     *
     * @return the value of player.roleId
     *
     * @mbg.generated Mon Aug 10 12:46:49 CST 2020
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.roleId
     *
     * @param roleid the value for player.roleId
     *
     * @mbg.generated Mon Aug 10 12:46:49 CST 2020
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.name
     *
     * @return the value of player.name
     *
     * @mbg.generated Mon Aug 10 12:46:49 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.name
     *
     * @param name the value for player.name
     *
     * @mbg.generated Mon Aug 10 12:46:49 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Mon Aug 10 12:46:49 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}