package com.database.mapper;

import com.database.entity.Player;
import com.database.entity.PlayerExample;
import com.database.entity.PlayerKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Aug 06 17:05:08 CST 2020
     */
    long countByExample(PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Aug 06 17:05:08 CST 2020
     */
    int deleteByExample(PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Aug 06 17:05:08 CST 2020
     */
    int deleteByPrimaryKey(PlayerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Aug 06 17:05:08 CST 2020
     */
    int insert(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Aug 06 17:05:08 CST 2020
     */
    int insertSelective(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Aug 06 17:05:08 CST 2020
     */
    List<Player> selectByExample(PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Aug 06 17:05:08 CST 2020
     */
    Player selectByPrimaryKey(PlayerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Aug 06 17:05:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") Player record, @Param("example") PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Aug 06 17:05:08 CST 2020
     */
    int updateByExample(@Param("record") Player record, @Param("example") PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Aug 06 17:05:08 CST 2020
     */
    int updateByPrimaryKeySelective(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Aug 06 17:05:08 CST 2020
     */
    int updateByPrimaryKey(Player record);
}